---
# using the container from https://github.com/growlf/docker-apt-cacher-ng/blob/master/acng.conf
- name: Create portainer/portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    ports:
      - "{{ portainer_ip }}:9000:9000"
    restart_policy: unless-stopped
    detach: true
    pull: true
    volumes:
      - /opt/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure backup directory for portainer
  ansible.builtin.file:
    path: /mnt/backup/docker/
    state: directory
    mode: "0750"
    owner: root
    group: root

# temp fix for https://github.com/portainer/portainer/issues/2046
- name: Ensure portainer git bugfix for /data
  ansible.builtin.file:
    src: /opt/portainer/data
    dest: /data
    owner: root
    group: root
    state: link

# ensure that docker-compose is located in /usr/bin/docker-compose
- name: Install docker-compose trough packages
  ansible.builtin.package:
    name: docker-compose
    state: present

# deploy docker-compose script for systemd
- name: Deploy systemd docker-compose service
  ansible.builtin.copy:
    src: docker-compose@.service
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

# configure rsyslog to not fill up logfiles
- name: Deploy rsyslog config for docker-compose
  ansible.builtin.copy:
    src: docker-compose-rsyslog.conf
    dest: /etc/rsyslog.d/00-docker-compose.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload rsyslog
