---
# using the container from https://github.com/growlf/docker-apt-cacher-ng/blob/master/acng.conf
- name: Create portainer/portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce
    ports:
      - "{{ portainer_ip }}:9000:9000"
      - "{{ portainer_ip }}:9443:9443"
    restart_policy: unless-stopped
    detach: true
    pull: true
    volumes:
      - /opt/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Ensure backup directory for portainer
  ansible.builtin.file:
    path: /mnt/backup/docker/
    state: directory
    mode: "0750"
    owner: root
    group: root
  become: true
  become_user: root

# temp fix for https://github.com/portainer/portainer/issues/2046
- name: Ensure portainer git bugfix for /data
  ansible.builtin.file:
    src: /opt/portainer/data
    dest: /data
    owner: root
    group: root
    state: link
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root

- name: Install docker-compose trough packages
  ansible.builtin.package:
    name: docker-compose
    state: present
  become: true
  become_user: root
  when: not portainer_docker_compose_v2 | bool

- name: Install docker-compose trough packages
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present
  become: true
  become_user: root
  when: portainer_docker_compose_v2 | bool

- name: Deploy systemd docker-compose service unit
  ansible.builtin.copy:
    src: docker-compose-v1@.service
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  become: true
  become_user: root
  when: not portainer_docker_compose_v2 | bool

- name: Deploy systemd docker-compose service unit
  ansible.builtin.copy:
    src: docker-compose-v2@.service
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  become: true
  become_user: root
  when: portainer_docker_compose_v2 | bool

- name: Deploy rsyslog config for docker-compose
  ansible.builtin.copy:
    src: docker-compose-rsyslog.conf
    dest: /etc/rsyslog.d/00-docker-compose.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload rsyslog
  become: true
  become_user: root

- name: Deploy systemd docker-prune service unit
  ansible.builtin.template:
    src: docker-prune.service.jinja2
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  become: true
  become_user: root

- name: Deploy systemd docker-prune timer unit
  ansible.builtin.copy:
    src: docker-prune.timer
    dest: /etc/systemd/system/docker-prune.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
  become: true
  become_user: root

- name: Start and enable systemd docker-prune timer unit
  ansible.builtin.systemd_service:
    name: docker-prune.timer
    state: started
    enabled: true
    daemon_reload: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
