---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  become_user: root

- name: Reload rsyslog
  ansible.builtin.service:
    name: rsyslog.service
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  become: true
  become_user: root
